import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#4d4635",
        "on-primary-fixed": "#241a00",
        "tertiary": "#b8d1f1",
        "inverse-surface": "#dae2fd",
        "surface-container-high": "#222a3d",
        "on-tertiary": "#19324b",
        "surface-tint": "#e9c349",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        "tertiary-container": "#9db5d4",
        "tertiary-fixed-dim": "#b0c9e8",
        "secondary": "#aec9e8",
        "surface-container-lowest": "#060e20",
        "on-tertiary-container": "#2f4761",
        "on-tertiary-fixed": "#011d35",
        "surface-dim": "#0b1326",
        "on-surface-variant": "#d0c5af",
        "secondary-container": "#2e4963",
        "surface-container-highest": "#2d3449",
        "on-secondary-fixed-variant": "#2e4963",
        "surface-bright": "#31394d",
        "secondary-fixed": "#cfe5ff",
        "outline": "#99907c",
        "on-primary-fixed-variant": "#574500",
        "on-error": "#690005",
        "secondary-fixed-dim": "#aec9e8",
        "on-secondary-container": "#9cb8d6",
        "primary-container": "#d4af37",
        "background": "#0b1326",
        "surface": "#0b1326",
        "inverse-primary": "#735c00",
        "on-secondary": "#15324b",
        "error-container": "#93000a",
        "surface-container-low": "#131b2e",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed-variant": "#314863",
        "on-background": "#dae2fd",
        "on-primary-container": "#554300",
        "popover": "#060e20",
        "popover-foreground": "#dae2fd",
        "primary": "#f2ca50",
        "surface-container": "#171f33",
        "tertiary-fixed": "#d1e4ff",
        "inverse-on-surface": "#283044",
        "on-error-container": "#ffdad6",
        "on-surface": "#dae2fd",
        "on-secondary-fixed": "#001d33",
        "error": "#ffb4ab",
        "on-primary": "#3c2f00",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "80px",
        "container-max-width": "1280px",
        "base": "8px",
        "margin-mobile": "20px",
        "gutter-desktop": "24px",
      },
      fontFamily: {
        montserrat: ["var(--font-montserrat)", "sans-serif"],
        manrope: ["var(--font-manrope)", "sans-serif"],
        "jetbrains-mono": ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.5s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
